const companyActionTypes = {
    GET_COMPANY_DATA_START : 'GET_COMPANY_DATA_START',
    GET_COMPANY_DATA_SUCCESS: 'GET_COMPANY_DATA_SUCCESS',
    GET_COMPANY_DATA_FAILURE: 'GET_COMPANY_DATA_FAILURE',
    REMOVE_CURRENT_COMPANY: 'REMOVE_CURRENT_COMPANY',
    GET_COMPANY_EMPLOYEES_START: 'GET_COMPANY_EMPLOYEES_START',
    GET_COMPANY_EMPLOYEES_SUCCESS: 'GET_COMPANY_EMPLOYEES_SUCCESS',
    GET_COMPANY_EMPLOYEES_FAILURE: 'GET_COMPANY_EMPLOYEE_FAILURE',
    UPDATE_COMPANY_START: 'UPDATE_COMPANY_START',
    UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
    UPDATE_COMPANY_FAILURE: 'UPDATE_COMPANY_FAILURE'
}

export default companyActionTypes;