const companyActionTypes = {
    GET_COMPANY_DATA_START : 'GET_COMPANY_DATA_START',
    GET_COMPANY_DATA_SUCCESS: 'GET_COMPANY_DATA_SUCCESS',
    GET_COMPANY_DATA_FAILURE: 'GET_COMPANY_DATA_FAILURE',
    REMOVE_CURRENT_COMPANY: 'REMOVE_CURRENT_COMPANY'
}

export default companyActionTypes;