const userActionTypes = {
    SIGNUP_USER_START: 'SIGNUP_USER_START',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILURE: 'SIGNUP_USER_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNIN_USER_START: 'SIGNIN_USER_START',
    SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
    SIGNIN_USER_FAILURE: 'SIGNIN_USER_FAILURE',
    SIGNOUT_USER_START: 'SIGNOUT_USER_START',
    SIGNOUT_USER_SUCCESS: 'SIGNOUT_USER_SUCCESS',
    SIGNOUT_USER_FAILURE: 'SIGNOUT_USER_FAILURE'
}


export default userActionTypes;